### PR TITLE
Add printf and exception callbacks

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
Add functions to enable setting of a printf and exception callback in the lower level CA layer

### CODE REVIEW

**Comment by xiaoqiangwang** [comment]
The callbacks _printf_ and _exception_handler_ apply to all channels and they don't take chid as a parameter. Would it be more appropriate to make them class methods?

**Comment by FreddieAkeroyd** [comment]
Yes, that is a good point.  I've come across a separate problem with using the functions though. The CA documentation says the library will only run one user callback at a time, and it would appear that when the callback to display an exception in python is installed it interferes the one that updates the channel state from running at the right time. So we had some python code that was checking state() on a PV in CaChannel and it started getting incorrect results after I added the exception callback. I've not really delved into channel access in detail at that level, but does it mean another thread would be needed to do the actual running of python callbacks to avoid blocking the CA library?

**Comment by xiaoqiangwang** [comment]
Callbacks are run sequentially by CA library threads. But unless there is time consuming code inside the exception callback, I don't see the other callbacks should suffer. Any code to demonstrate this problem?

**Comment by xiaoqiangwang** [comment]
I could see a possible explanation for your problem. CaChannel module postpones the creation of channel access context (preemptive) until actual channels are created. If your call to `ca.add_exception_event` precedes any channels creation, a non-preemptive channel access context will be created by CA library.

In a non-preemptive context the callbacks will only happen inside the call to ca.pend_event. Otherwise you see stale PV state/values.

The solution is to call `ca.create_context(True)` before calling `ca.add_exception_event`.

**Comment by FreddieAkeroyd** [comment]
Thank you for your quick response and suggestion - that was indeed the problem. I had installed the handlers after creating a CaChannel object but before any channel access calls, so it was now ending up with a non preemptive context. I added your suggested fix last night and all the tests that were failing before were running fine overnight. I owe you a drink (or equivalent) :-)

**Comment by xiaoqiangwang** [comment]
Very well. Would you make the conversion to class methods? Or I can merge this PR and make the changes.

**Comment by FreddieAkeroyd** [comment]
I've changed them to class method, thanks for all your help.

**Comment by xiaoqiangwang** [comment]
PS:  Commit e7817dc automatically attaches to the default channel access context. This would avoid explicit call of `ca.create_context`.

**Pull request merged**
